<?php

// include_paths.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    $vendorDir . '/phpunit/phpunit-mock-objects',
    $vendorDir . '/phpunit/php-file-iterator',
    $vendorDir . '/phpunit/phpunit',
    $vendorDir . '/symfony/yaml',
);
